/**
 * Shipped. — Weekly + Monthly Sweep Data (AUTO-GENERATED)
 *
 * DO NOT EDIT BY HAND. Regenerated by:
 *
 *     node scripts/build-daily-manifest.mjs
 *
 * Source: the origin/daily-pages branch of the shipped repo (anthropic-weekly/,
 * anthropic-monthly/). Published at eddiebelaval.github.io/shipped.
 *
 * These are the ROUTINE sweeps, distinct from the numbered magazine issues
 * in issues.data.ts. Newest period first.
 *
 * Last generated: 2026-07-27 (11 weekly, 1 monthly)
 */

export interface ShippedSweep {
  /** Period key: ISO year-week for weekly ("2026-29"), year-month for monthly ("2026-06") */
  period: string
  /** Human label, e.g. "Week of July 13-19, 2026" or "June 2026" */
  label: string
  /** ISO date the period starts, for sorting */
  sortKey: string
  /** Editorial standfirst for the sweep */
  title: string
  /** Published public URL (github.io) */
  url: string
  /** Approximate visible word count */
  wordCount: number
}

/** Weekly Anthropic sweeps, newest first. */
export const SHIPPED_WEEKLY_SWEEPS: ShippedSweep[] = [
  {
    period: '2026-30',
    label: 'Week of July 20-26, 2026',
    sortKey: '2026-07-20',
    title: 'Four Claude Code releases. A $200M economics research bet. Then Opus 5 landed Friday and made Fable 5 look expensive.',
    url: 'https://eddiebelaval.github.io/shipped/anthropic-weekly/2026-30.html',
    wordCount: 2207,
  },
  {
    period: '2026-29',
    label: 'Week of July 13-19, 2026',
    sortKey: '2026-07-13',
    title: 'Claude for Teachers, Artifacts multiplayer, Claude Code caps, MCP Tunnels, Dreaming API. Five days. One through-line: make the boundaries legible.',
    url: 'https://eddiebelaval.github.io/shipped/anthropic-weekly/2026-29.html',
    wordCount: 2104,
  },
  {
    period: '2026-28',
    label: 'Week of July 6-12, 2026',
    sortKey: '2026-07-06',
    title: 'Five versions of Claude Code, a government scan of 466 million lines, a question submitted by 52,000 people, and an undocumented SDK flag called dreaming. That is week 28.',
    url: 'https://eddiebelaval.github.io/shipped/anthropic-weekly/2026-28.html',
    wordCount: 2844,
  },
  {
    period: '2026-27',
    label: 'Week of June 29 - July 5, 2026',
    sortKey: '2026-06-29',
    title: 'Claude Sonnet 5 became the default for every Free and Pro user. Fable 5 returned after 19 days of export control. Claude Code shipped six releases and flipped to Manual mode. Agent memory is three weeks out.',
    url: 'https://eddiebelaval.github.io/shipped/anthropic-weekly/2026-27.html',
    wordCount: 3116,
  },
  {
    period: '2026-26',
    label: 'Week of June 22-28, 2026',
    sortKey: '2026-06-22',
    title: 'Anthropic only. Week of 2026-06-22 to 2026-06-26. 11 log entries, 7 sections. Published by id8Labs.',
    url: 'https://eddiebelaval.github.io/shipped/anthropic-weekly/2026-26.html',
    wordCount: 2304,
  },
  {
    period: '2026-25',
    label: 'Week of June 15-21, 2026',
    sortKey: '2026-06-15',
    title: 'A billing policy announced on Monday was reversed by Tuesday. The rest of the week was release velocity.',
    url: 'https://eddiebelaval.github.io/shipped/anthropic-weekly/2026-25.html',
    wordCount: 1546,
  },
  {
    period: '2026-23',
    label: 'Week of June 1-7, 2026',
    sortKey: '2026-06-01',
    title: 'The week Anthropic filed its S-1, set a public timeline for Mythos, deprecated Opus 4.1, and shipped six Claude Code builds.',
    url: 'https://eddiebelaval.github.io/shipped/anthropic-weekly/2026-23.html',
    wordCount: 1401,
  },
  {
    period: '2026-22',
    label: 'Week of May 25-31, 2026',
    sortKey: '2026-05-25',
    title: 'Anthropic raised $65 billion at a near-trillion valuation, shipped a flagship model, and told customers the model it withheld for safety arrives in weeks.',
    url: 'https://eddiebelaval.github.io/shipped/anthropic-weekly/2026-22.html',
    wordCount: 1384,
  },
  {
    period: '2026-21',
    label: 'Week of May 18-24, 2026',
    sortKey: '2026-05-18',
    title: 'Anthropic bought the company that built everyone\'s SDKs and shut it down. Claude Code shipped five times.',
    url: 'https://eddiebelaval.github.io/shipped/anthropic-weekly/2026-21.html',
    wordCount: 1185,
  },
  {
    period: '2026-20',
    label: 'Week of May 11-17, 2026',
    sortKey: '2026-05-11',
    title: 'Claude went into AWS accounts, small business software, and a $200 million partnership with the organization trying to eradicate polio.',
    url: 'https://eddiebelaval.github.io/shipped/anthropic-weekly/2026-20.html',
    wordCount: 1914,
  },
  {
    period: '2026-19',
    label: 'Week of May 4-10, 2026',
    sortKey: '2026-05-04',
    title: 'CPO Ami Vora opened "Code with Claude 2026" at 09:00 PT on Wednesday in San Francisco with a line that should have cued the crowd: "This event is about how we are making our products work better for you." No keynote model reveal. What the stage delivered instead was a set of agentic features that Anthropic has apparently been running internally long enough to build confidence in.',
    url: 'https://eddiebelaval.github.io/shipped/anthropic-weekly/2026-19.html',
    wordCount: 2013,
  },
]

/** Monthly Anthropic roundups, newest first. */
export const SHIPPED_MONTHLY_SWEEPS: ShippedSweep[] = [
  {
    period: '2026-06',
    label: 'June 2026',
    sortKey: '2026-06-01',
    title: 'Two launches, two retirements, one new default. Fable 5 was the best model available on June 9; it was suspended on June 12. Sonnet 5 became the default on June 30.',
    url: 'https://eddiebelaval.github.io/shipped/anthropic-monthly/2026-06.html',
    wordCount: 5550,
  },
]
