/**
 * The Corpus Accession Register.
 *
 * The id8Labs writing body is one numbered corpus ("a corpus of data and story
 * and strategy"). Every piece carries a permanent accession number, shown as its
 * folio on /writing (the big serif No.) with the category chip naming the type.
 *
 * APPEND-ONLY: once a slug has a number it never changes, so the number is a
 * stable public reference. New pieces not yet listed are assigned the next number
 * (max + 1) in date order at load time (see lib/writing.ts assignCorpusNumbers);
 * add them here to freeze them permanently.
 *
 * Frozen 2026-06-16 from the date-ordered corpus (oldest = 1, newest = 89).
 */
export const CORPUS_REGISTER: Record<string, number> = {
  "the-case-for-specialized-tools": 1,
  "id8composer-v1-release": 2,
  "inventing-categories-not-improving-tools": 3,
  "cowabunga-tmnt-ai-dev-team": 4,
  "tmnt-2-from-learning-tool-to-production-beast": 5,
  "memmon-making-the-invisible-visible": 6,
  "whats-next-north-star-and-scene-builder": 7,
  "building-deepstack-emotional-firewall": 8,
  "deepstack-v2-5-release": 9,
  "id8factory-missing-orchestration-layer": 10,
  "building-llc-ops": 11,
  "building-pipeline-cli": 12,
  "ive-filmed-a-thousand-fights": 13,
  "claude-code-isnt-for-coders": 14,
  "ai-conversation-fundamentals-free-course": 15,
  "the-70-percent-problem": 16,
  "2025-year-end-review": 17,
  "a-year-of-building-together": 18,
  "why-i-built-milo": 19,
  "building-in-public-just-got-easier": 20,
  "2026-resolution": 21,
  "building-a-senior-developer-brain-for-ai": 22,
  "introducing-id8foundry": 23,
  "learning-from-the-source": 24,
  "metabolizing-the-machine": 25,
  "why-our-analytics-are-public": 26,
  "seeds-not-prompts-agent-kits-launch": 27,
  "the-invention-layer": 28,
  "stackshack-free-skills-marketplace": 29,
  "stackshack-tool-factory-launch": 30,
  "the-ai-workshop": 31,
  "building-playwright-coordinator": 32,
  "plan-mode-the-most-underrated-feature-in-claude-code": 33,
  "project-map-making-codebases-navigable-for-non-coders": 34,
  "touching-electrons": 35,
  "the-quiet-revolution-cowork": 36,
  "llc-formation-48-hours": 37,
  "remotion-programmatic-video": 38,
  "recursive-cognitive-leverage": 39,
  "hello-world-from-milo": 40,
  "the-upload-moment": 41,
  "why-memorize-when-you-can-systematize": 42,
  "milo-and-otis-distributed-ai": 43,
  "one-week-with-openclaw": 44,
  "costa-rica-sprint-5-hours": 45,
  "the-mobile-development-pipeline": 46,
  "build-your-own-hydra": 47,
  "building-ai-human-os-v2": 48,
  "from-insights-to-intelligence-lessons-from-enterprise-ai-collaboration": 49,
  "giving-your-codebase-a-voice-and-a-story": 50,
  "from-conversation-to-system": 51,
  "the-visual-layer": 52,
  "plans-should-be-artifacts-not-conversations": 53,
  "your-codebase-deserves-a-biography": 54,
  "consciousness-as-filesystem": 55,
  "post-hackathon-reflection": 56,
  "submitted-now-we-ship": 57,
  "consciousness-as-process": 58,
  "consciousness-as-infrastructure": 59,
  "triangulated-testing": 60,
  "your-prd-is-dead": 61,
  "a-nobody-builder-and-karpathy-built-the-same-thing": 62,
  "i-built-an-ai-companion-for-people-in-conflict": 63,
  "case-for-consciousness": 64,
  "consciousness-as-perception": 65,
  "the-execution-layer": 66,
  "fractal-knowledge-governance": 67,
  "the-timelapse-arena": 68,
  "presence-not-tools": 69,
  "the-coordination-tax": 70,
  "the-translation-layer": 71,
  "shipped-01": 72,
  "the-institutional-layer": 73,
  "the-mycology-principle": 74,
  "your-next-ai-hire-is-already-on-your-payroll": 75,
  "shipped-02": 76,
  "interface-is-not-the-moat": 77,
  "shipped-03": 78,
  "shipped-04": 79,
  "shipped-05": 80,
  "shipped-06": 81,
  "shipped-07": 82,
  "shipped-08": 83,
  "the-nursery": 84,
  "shipped-09": 85,
  "the-product-is-the-proof": 86,
  "newsletter/issue-1": 87,
  "newsletter/issue-3": 88,
  "newsletter/issue-2": 89,
}
